services:
  mysql:
    container_name: mysql-ku
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mantap123
    volumes:
      - mysql-dari-compose:/var/lib/mysql

volumes:
  mysql-dari-compose:

  # nginx:
  #   container_name: nginx-ku
  #   image: nginx:alpine
    # depends_on:
    #   - mysql
    # ports:
    #   - 8080:80
    # command: 
    # - /bin/bash
    # - -c
    # - |
    #   echo "nginx dari array style 1" > /usr/share/nginx/html/index/html/index.html
    #   nginx -g 'daemon off;'

  # nginx2:
  #   container_name: nginx-ku2
  #   image: nginx:alpine
  #   # depends_on:
  #   #   - mysql
  #   ports:
  #     - 8081:80
  #   command: [l"sh", "-c", "echo 'nginx dari array 2 mantap' > /usr/share/nginx/html/index/html/index.html && nginx -g 'daemon off;'" ]
      


  # mysql:
  #   container_name: mysql-ku
  #   image: mysql:8.0
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=mantap123

  
  # nodejs:
  #   container_name: node-ku
  #   build: 
  #     context: ./docker/nodejs
  #     dockerfile: Dockerfile.staging
  #   ports:
  #     - 5656:5656
  #   command: app.js