services:
  nginx-1:
    container_name: nginx-ku1
    image: nginx:alpine
    build: 
      context: ./docker/nginx
      dockerfile: Dockerfile.staging
      args:
        - VERSION=1.1.1

  nodejs:
    container_name: node-ku
    build: 
      context: ./docker/nodejs
      dockerfile: Dockerfile.staging
    